server:
  port: 9991
  servlet:
    context path: "/bus/mgmt/v1"

spring:
  application:
    name: bus
  mvc:
    path match:
      matching-strategy: ant-path-matcher

  data:
    mongodb:
      user: admin
      password: admin
      database: bus-booking-system
      uri: mongodb://localhost:27017
config:
  rest:
    service:
      user-url: "http://localhost:9990/user/mgmt/v1"
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#config:
#  rest:
#    service:
#      encryptionKey: "keycodevalue"

